server:
  port: 8080
spring:
  redis:
    host:
    port:
    password:
    database: 0
    jedis:
      pool:
        max-active: 1000
        max-idle: 200
        min-idle: 50
        max-wait: 3s
    timeout: 3s
  datasource:
    druid:
      url: jdbc:mysql:&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: aicity
      password: huazhen@123
      maxActive: 1000
      initialSize: 10
      maxWait: 3000
      minIdle: 50
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        allow:
  security:
    user:
      name: admin
      password: admin
    disableUISecurity: true
  thread-pool:
    defaultThreadPool:
      name: default-pool-
      corePoolSize: 50
      maxPoolSize: 200
      keepAliveSeconds: 60
      queueCapacity: 200
    smsThreadPool:
      name: sms-pool-
      corePoolSize: 10
      maxPoolSize: 50
      keepAliveSeconds: 60
      queueCapacity: 50
jetcache:
  statIntervalMinutes: 60
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      limit: 100
      expireAfterWriteInMillis: 600000
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      database: ${spring.redis.database}
      password: ${spring.redis.password}
management:
  endpoints:
    web:
      exposure:
        include: health
aliyun:
  accessKeyId:
  accessKeySecret:
  sms:
    enable: false
    regionId: cn-beijing
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 172.16.12.65:22122
  read-url: http://172.16.12.65:8888
web:
  domain:
    h5: http://172.16.13.248:8088
juhe:
  appkey: thisisappkey
  weatherUrl: http://apis.juhe.cn/simpleWeather/query
